[package]
name = "reminders"
version = "0.1.0"
description = "Reminders desktop app"
edition = "2021"

[lib]
name = "reminders_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
app-core = { path = "../../../../crates/core" }
app-config = { path = "../../../../crates/config" }
data-client = { path = "../../../../crates/client" }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-clipboard-manager = "2"
